// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzzwceamyuuvvughfcwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6endjZWFteXV1dnZ1Z2hmY3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTUxMDUsImV4cCI6MjA1OTgzMTEwNX0.7GCzksw3zKoukn2eGWGf5ZO6suk7oooDww50Sygtdyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);